# Generated by Django 3.2.6 on 2021-09-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='titel',
            new_name='title',
        ),
    ]
